### ISSUE TITLE
Questions about the adaptive bandwidth

### ISSUE THREAD

**Issue by bright1993ff66** [JeremyGelb/spNetwork#14]
Thank you for contributing to spatial data science by creating and maintaining such a marvelous package!

I am working on a density estimation project, and the task is to compute the network densities of accidents across a road network. By following the [Network KDE](https://cran.r-project.org/web/packages/spNetwork/vignettes/NKDE.html#ref-okabe2012spatial) tutorial, I am able to compute the network KDE of point features on the roads.

But I still have one question about the calculation of adaptive bandwidth. Here, it seems like you calculate the bandwidth for each event (in my case, accident):

![Computing the Adaptive Bandwidth](https://user-images.githubusercontent.com/29517359/220815273-098f828e-1be0-468c-8998-df1702b505ea.png)

But how the bandwidth for the sample points are actually calculated? You mentioned that ```The densities at sampling points are then evaluated by using the obtained vector of bandwidth for each event```, which is not quite clear. Can you give a more detailed description of this? Thank you very much for your time!

**Comment by JeremyGelb** [comment]
Hello there !

The sentence is indeed not very clear. In spNetwork, to reduce the computation time, the adaptive bandwidths are calculated only at the events' locations. Then, they are used to "spread the weight" of the events around them. Each sampling point within this bandwidth will receive a part of its weight. 

Here is another explanation from the article in the Rjournal :
"""
Second, the calculus of the density is event-oriented. In other words, the kernel density is
sequentially calculated around each event. The density values of the samples are updated at each
iteration. The advantage of this approach is that the calculation time is less affected by the density of
the sampling points.
"""

**Comment by bright1993ff66** [comment]
@JeremyGelb Thank you for your feedback! It makes more sense to me now 😃

**Comment by JeremyGelb** [comment]
Perfect! I close the issue. Feel free to open a new one if you have another question.
