### ISSUE TITLE
Adaptive Bandwidth in Temporal Network Kernel Density Estimation

### ISSUE THREAD

**Issue by bright1993ff66** [JeremyGelb/spNetwork#17]
Dear @JeremyGelb , Thanks again for creating such a great package for GIS analysis!

I am using [tnkde](https://cran.r-project.org/web/packages/spNetwork/vignettes/TNKDE.html) to analyze the kernel densities of collision records in the city. However, I am not sure if I understand the adaptive bandwidth in this case clearly. In the [nkde](https://cran.r-project.org/web/packages/spNetwork/vignettes/NKDE.html#an-example-with-adaptive-bandwidth) function, the adaptive bandwidth is computed as the following:

![image](https://github.com/JeremyGelb/spNetwork/assets/29517359/a0c11b0b-88eb-4305-8166-7cae666ea071)

My question is in the [tnkde](https://cran.r-project.org/web/packages/spNetwork/vignettes/TNKDE.html) case, does $h_0$ become a vector of reference bandwidth in space and time ($h_0 = [h_{0, space}, h_{0, time}]$)? Since both $\gamma_{f}$ and $\tilde{f}h_0(e_i)$ are still float numbers, the $h(e_i)$ now also becomes a vector of bandwidth $[h_{e_i, space}, h_{e_i, time}]$ for event $e_i$?

Thank you for your time!

**Comment by JeremyGelb** [comment]
Hello @bright1993ff66 , 

There are two ways in spNetwork to use adaptive bandwidth for TNKDE : separated and simultaneous.

In the first case, for each event, a local temporal bandwidth is calculated for each event location (Uei) based on the densities calculated in time with h0 the reference bandwidth in time. Then the same thing is done with the spatial (network) dimension. In this case, you consider that space and time are not interacting (weak spatio-temporal autocorrelation)
![image](https://github.com/JeremyGelb/spNetwork/assets/46856737/79ab7406-4c6a-4d7c-8d46-b28a4b94aac5)

In the second case, the spatio-temporal density is estimated at each event location using simultaneously the time and network reference bandwidths. Then, the temporal and network bandwidths are obtained by replacing h0 in the above formula.
![image](https://github.com/JeremyGelb/spNetwork/assets/46856737/1f2eddc7-3d86-4aa5-aa15-21c647bf16a4)

I have written a paper presenting formally the TNKDE and it was just accepted in the journal Geographical Analysis. I will share with here the submitted manuscript as soon as possible. It gives a detailed description of the method.

**Comment by bright1993ff66** [comment]
@JeremyGelb Thanks! And Congrats on your paper acceptance! 

Looking forward to reading your paper 👍

**Comment by JeremyGelb** [comment]
The paper is now published and open access here : https://onlinelibrary.wiley.com/doi/10.1111/gean.12368
