### ISSUE TITLE
Remove compiled object files from src directory

### ISSUE THREAD

**Issue by mpadge** [JeremyGelb/spNetwork#9]
Hi @JeremyGelb, I was checking out your package to help inform upcoming standards for network software as part of [rOpenSci's project for peer review of statistical software](https://stats-devguide.ropensci.org), and noticed you've got a bunch of files in your `src` directory which should be `.gitignore`d. You shouldn't commit `.o` or `.dll` files - just add these patterns to `.gitignore` to stop this happening in the future. Removing these will considerably reduce the size of the repo for anybody cloning it. Thanks!

---

Also: Great work on putting together this fantastic package. Lots of your routines provide nice enhancements to the kinds of stuff in [my `dodgr` package](https://github.com/atfutures/dodgr). Very nice!

**Comment by JeremyGelb** [comment]
Hi @mpadge ! Thank you for the suggestion ! I just added the patterns to the gitignore file. it will be updated soon on github (I am working on an issue currently). Thank you very much for your interest in spNetwork !

**Comment by JeremyGelb** [comment]
done !
